/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *
 *                 This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                 Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                 All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  LICENSE
 *  -------------------------------------------------------------------------------------------------------------------
 *            Module: VTTCntrl
 *           Program: MSR_Vector_SLP4
 *          Customer: AUTOSAR 4 Evaluation Bundle for CANoe/VTT
 *       Expiry Date: Not restricted
 *  Ordered Derivat.: VTT
 *    License Scope : The usage is restricted to CBD1500710_D05
 *
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *              File: VttCntrl_Cfg.c
 *   Generation Time: 2019-11-13 15:54:52
 *           Project: Bootcamp - Version 1.0
 *          Delivery: CBD1500710_D05
 *      Tool Version: DaVinci Configurator (beta) 5.16.27
 *
 *
 *********************************************************************************************************************/

/**********************************************************************************************************************
 ! BETA VERSION                                                                                                       !
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! These programs are fully operative programs. With regard to the fact that the programs are a beta-version only,    !
 ! Vector Informatik's liability shall be expressly excluded in cases of ordinary negligence, to the extent           !
 ! admissible by law or statute.                                                                                      !
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
**********************************************************************************************************************/


#define VTTCNTRL_CFG_SOURCE

/**********************************************************************************************************************
 * INCLUDES
 *********************************************************************************************************************/

#include "VttCntrl_Cfg.h"
#include "CANoeApi.h"
#include "CANoeEmuProcessor.h"
#include "Os.h"

/**********************************************************************************************************************
*  GLOBAL DATA
**********************************************************************************************************************/

int irqMap[IRQ_COUNT] = {
/* 0 */ IRQ_UNHANDLED,
/* 1 */ IRQ_UNHANDLED,
/* 2 */ IRQ_UNHANDLED,
/* 3 */ IRQ_UNHANDLED,
/* 4 */ IRQ_UNHANDLED,
/* 5 */ OS_IRQ_CanIsrTx_0,
/* 6 */ OS_IRQ_CanIsrRx_0,
/* 7 */ OS_IRQ_CanIsrErr_0,
/* 8 */ IRQ_UNHANDLED,
/* 9 */ IRQ_UNHANDLED,
/* 10 */ IRQ_UNHANDLED,
/* 11 */ IRQ_UNHANDLED,
/* 12 */ IRQ_UNHANDLED,
/* 13 */ IRQ_UNHANDLED,
/* 14 */ IRQ_UNHANDLED,
/* 15 */ IRQ_UNHANDLED,
/* 16 */ IRQ_UNHANDLED,
/* 17 */ IRQ_UNHANDLED,
/* 18 */ IRQ_UNHANDLED,
/* 19 */ IRQ_UNHANDLED,
/* 20 */ IRQ_UNHANDLED,
/* 21 */ IRQ_UNHANDLED,
/* 22 */ IRQ_UNHANDLED,
/* 23 */ IRQ_UNHANDLED,
/* 24 */ IRQ_UNHANDLED,
/* 25 */ IRQ_UNHANDLED,
/* 26 */ IRQ_UNHANDLED,
/* 27 */ IRQ_UNHANDLED,
/* 28 */ IRQ_UNHANDLED,
/* 29 */ IRQ_UNHANDLED,
/* 30 */ IRQ_UNHANDLED,
/* 31 */ IRQ_UNHANDLED,
/* 32 */ IRQ_UNHANDLED,
/* 33 */ IRQ_UNHANDLED,
/* 34 */ IRQ_UNHANDLED,
/* 35 */ IRQ_UNHANDLED,
/* 36 */ IRQ_UNHANDLED,
/* 37 */ IRQ_UNHANDLED,
/* 38 */ IRQ_UNHANDLED,
/* 39 */ IRQ_UNHANDLED,
/* 40 */ IRQ_UNHANDLED,
/* 41 */ IRQ_UNHANDLED,
/* 42 */ IRQ_UNHANDLED,
/* 43 */ IRQ_UNHANDLED,
/* 44 */ IRQ_UNHANDLED,
/* 45 */ IRQ_UNHANDLED,
/* 46 */ IRQ_UNHANDLED,
/* 47 */ IRQ_UNHANDLED,
/* 48 */ IRQ_UNHANDLED,
/* 49 */ IRQ_UNHANDLED,
/* 50 */ IRQ_UNHANDLED,
/* 51 */ IRQ_UNHANDLED,
/* 52 */ IRQ_UNHANDLED,
/* 53 */ IRQ_UNHANDLED,
/* 54 */ IRQ_UNHANDLED,
/* 55 */ IRQ_UNHANDLED,
/* 56 */ IRQ_UNHANDLED,
/* 57 */ IRQ_UNHANDLED,
/* 58 */ IRQ_UNHANDLED,
/* 59 */ IRQ_UNHANDLED,
/* 60 */ IRQ_UNHANDLED,
/* 61 */ IRQ_UNHANDLED,
/* 62 */ IRQ_UNHANDLED,
/* 63 */ IRQ_UNHANDLED,
/* 64 */ IRQ_UNHANDLED,
/* 65 */ IRQ_UNHANDLED,
/* 66 */ IRQ_UNHANDLED,
/* 67 */ IRQ_UNHANDLED,
/* 68 */ IRQ_UNHANDLED,
/* 69 */ IRQ_UNHANDLED,
/* 70 */ IRQ_UNHANDLED,
/* 71 */ IRQ_UNHANDLED,
/* 72 */ IRQ_UNHANDLED,
/* 73 */ IRQ_UNHANDLED,
/* 74 */ IRQ_UNHANDLED,
/* 75 */ IRQ_UNHANDLED,
/* 76 */ IRQ_UNHANDLED,
/* 77 */ IRQ_UNHANDLED,
/* 78 */ IRQ_UNHANDLED,
/* 79 */ IRQ_UNHANDLED,
/* 80 */ IRQ_UNHANDLED,
/* 81 */ IRQ_UNHANDLED,
/* 82 */ IRQ_UNHANDLED,
/* 83 */ IRQ_UNHANDLED,
/* 84 */ IRQ_UNHANDLED,
/* 85 */ IRQ_UNHANDLED,
/* 86 */ IRQ_UNHANDLED,
/* 87 */ IRQ_UNHANDLED,
/* 88 */ IRQ_UNHANDLED,
/* 89 */ IRQ_UNHANDLED,
/* 90 */ IRQ_UNHANDLED,
/* 91 */ IRQ_UNHANDLED,
/* 92 */ IRQ_UNHANDLED,
/* 93 */ IRQ_UNHANDLED,
/* 94 */ IRQ_UNHANDLED,
/* 95 */ IRQ_UNHANDLED,
/* 96 */ IRQ_UNHANDLED,
/* 97 */ IRQ_UNHANDLED,
/* 98 */ IRQ_UNHANDLED,
/* 99 */ IRQ_UNHANDLED,
/* 100 */ IRQ_UNHANDLED,
/* 101 */ IRQ_UNHANDLED,
/* 102 */ IRQ_UNHANDLED,
/* 103 */ IRQ_UNHANDLED,
/* 104 */ IRQ_UNHANDLED,
/* 105 */ IRQ_UNHANDLED,
/* 106 */ IRQ_UNHANDLED,
/* 107 */ IRQ_UNHANDLED,
/* 108 */ IRQ_UNHANDLED,
/* 109 */ IRQ_UNHANDLED,
/* 110 */ IRQ_UNHANDLED,
/* 111 */ IRQ_UNHANDLED,
/* 112 */ IRQ_UNHANDLED,
/* 113 */ IRQ_UNHANDLED,
/* 114 */ IRQ_UNHANDLED,
/* 115 */ IRQ_UNHANDLED,
/* 116 */ IRQ_UNHANDLED,
/* 117 */ IRQ_UNHANDLED,
/* 118 */ IRQ_UNHANDLED,
/* 119 */ IRQ_UNHANDLED,
/* 120 */ IRQ_UNHANDLED,
/* 121 */ IRQ_UNHANDLED,
/* 122 */ IRQ_UNHANDLED,
/* 123 */ IRQ_UNHANDLED,
/* 124 */ OS_IRQ_GptIsr_0,
/* 125 */ IRQ_UNHANDLED,
/* 126 */ IRQ_UNHANDLED,
/* 127 */ IRQ_UNHANDLED,
/* 128 */ IRQ_UNHANDLED,
/* 129 */ IRQ_UNHANDLED,
/* 130 */ IRQ_UNHANDLED,
/* 131 */ IRQ_UNHANDLED,
/* 132 */ IRQ_UNHANDLED,
/* 133 */ IRQ_UNHANDLED,
/* 134 */ IRQ_UNHANDLED,
/* 135 */ IRQ_UNHANDLED,
/* 136 */ IRQ_UNHANDLED,
/* 137 */ IRQ_UNHANDLED,
/* 138 */ IRQ_UNHANDLED,
/* 139 */ IRQ_UNHANDLED,
/* 140 */ IRQ_UNHANDLED,
/* 141 */ IRQ_UNHANDLED,
/* 142 */ IRQ_UNHANDLED,
/* 143 */ IRQ_UNHANDLED,
/* 144 */ IRQ_UNHANDLED,
/* 145 */ IRQ_UNHANDLED,
/* 146 */ IRQ_UNHANDLED,
/* 147 */ IRQ_UNHANDLED,
/* 148 */ IRQ_UNHANDLED,
/* 149 */ IRQ_UNHANDLED,
/* 150 */ IRQ_UNHANDLED,
/* 151 */ IRQ_UNHANDLED,
/* 152 */ IRQ_UNHANDLED,
/* 153 */ IRQ_UNHANDLED,
/* 154 */ IRQ_UNHANDLED,
/* 155 */ IRQ_UNHANDLED,
/* 156 */ IRQ_UNHANDLED,
/* 157 */ IRQ_UNHANDLED,
/* 158 */ IRQ_UNHANDLED,
/* 159 */ IRQ_UNHANDLED,
/* 160 */ IRQ_UNHANDLED,
/* 161 */ IRQ_UNHANDLED,
/* 162 */ IRQ_UNHANDLED,
/* 163 */ IRQ_UNHANDLED,
/* 164 */ IRQ_UNHANDLED,
/* 165 */ IRQ_UNHANDLED,
/* 166 */ IRQ_UNHANDLED,
/* 167 */ IRQ_UNHANDLED,
/* 168 */ IRQ_UNHANDLED,
/* 169 */ IRQ_UNHANDLED,
/* 170 */ IRQ_UNHANDLED,
/* 171 */ IRQ_UNHANDLED,
/* 172 */ IRQ_UNHANDLED,
/* 173 */ IRQ_UNHANDLED,
/* 174 */ OS_IRQ_AdcIsr_0,
/* 175 */ IRQ_UNHANDLED,
/* 176 */ IRQ_UNHANDLED,
/* 177 */ IRQ_UNHANDLED,
/* 178 */ IRQ_UNHANDLED,
/* 179 */ IRQ_UNHANDLED,
/* 180 */ IRQ_UNHANDLED,
/* 181 */ IRQ_UNHANDLED,
/* 182 */ IRQ_UNHANDLED,
/* 183 */ IRQ_UNHANDLED,
/* 184 */ IRQ_UNHANDLED,
/* 185 */ IRQ_UNHANDLED,
/* 186 */ IRQ_UNHANDLED,
/* 187 */ IRQ_UNHANDLED,
/* 188 */ IRQ_UNHANDLED,
/* 189 */ IRQ_UNHANDLED,
/* 190 */ IRQ_UNHANDLED,
/* 191 */ IRQ_UNHANDLED,
/* 192 */ IRQ_UNHANDLED,
/* 193 */ IRQ_UNHANDLED,
/* 194 */ IRQ_UNHANDLED,
/* 195 */ IRQ_UNHANDLED,
/* 196 */ IRQ_UNHANDLED,
/* 197 */ IRQ_UNHANDLED,
/* 198 */ IRQ_UNHANDLED,
/* 199 */ IRQ_UNHANDLED,
/* 200 */ IRQ_UNHANDLED,
/* 201 */ IRQ_UNHANDLED,
/* 202 */ IRQ_UNHANDLED,
/* 203 */ IRQ_UNHANDLED,
/* 204 */ IRQ_UNHANDLED,
/* 205 */ IRQ_UNHANDLED,
/* 206 */ IRQ_UNHANDLED,
/* 207 */ IRQ_UNHANDLED,
/* 208 */ IRQ_UNHANDLED,
/* 209 */ IRQ_UNHANDLED,
/* 210 */ IRQ_UNHANDLED,
/* 211 */ IRQ_UNHANDLED,
/* 212 */ IRQ_UNHANDLED,
/* 213 */ IRQ_UNHANDLED,
/* 214 */ IRQ_UNHANDLED,
/* 215 */ IRQ_UNHANDLED,
/* 216 */ IRQ_UNHANDLED,
/* 217 */ IRQ_UNHANDLED,
/* 218 */ IRQ_UNHANDLED,
/* 219 */ IRQ_UNHANDLED,
/* 220 */ IRQ_UNHANDLED,
/* 221 */ IRQ_UNHANDLED,
/* 222 */ IRQ_UNHANDLED,
/* 223 */ IRQ_UNHANDLED,
/* 224 */ OS_IRQ_IcuIsr_0,
/* 225 */ IRQ_UNHANDLED,
/* 226 */ IRQ_UNHANDLED,
/* 227 */ IRQ_UNHANDLED,
/* 228 */ IRQ_UNHANDLED,
/* 229 */ IRQ_UNHANDLED,
/* 230 */ IRQ_UNHANDLED,
/* 231 */ IRQ_UNHANDLED,
/* 232 */ IRQ_UNHANDLED,
/* 233 */ IRQ_UNHANDLED,
/* 234 */ IRQ_UNHANDLED,
/* 235 */ IRQ_UNHANDLED,
/* 236 */ IRQ_UNHANDLED,
/* 237 */ IRQ_UNHANDLED,
/* 238 */ IRQ_UNHANDLED,
/* 239 */ IRQ_UNHANDLED,
/* 240 */ IRQ_UNHANDLED,
/* 241 */ IRQ_UNHANDLED,
/* 242 */ IRQ_UNHANDLED,
/* 243 */ IRQ_UNHANDLED,
/* 244 */ IRQ_UNHANDLED,
/* 245 */ IRQ_UNHANDLED,
/* 246 */ IRQ_UNHANDLED,
/* 247 */ IRQ_UNHANDLED,
/* 248 */ IRQ_UNHANDLED,
/* 249 */ IRQ_UNHANDLED,
/* 250 */ IRQ_UNHANDLED,
/* 251 */ IRQ_UNHANDLED,
/* 252 */ IRQ_UNHANDLED,
/* 253 */ IRQ_UNHANDLED,
/* 254 */ IRQ_UNHANDLED,
/* 255 */ IRQ_UNHANDLED,
/* 256 */ IRQ_UNHANDLED,
/* 257 */ IRQ_UNHANDLED,
/* 258 */ IRQ_UNHANDLED,
/* 259 */ IRQ_UNHANDLED,
/* 260 */ IRQ_UNHANDLED,
/* 261 */ IRQ_UNHANDLED,
/* 262 */ IRQ_UNHANDLED,
/* 263 */ IRQ_UNHANDLED,
/* 264 */ IRQ_UNHANDLED,
/* 265 */ IRQ_UNHANDLED,
/* 266 */ IRQ_UNHANDLED,
/* 267 */ IRQ_UNHANDLED,
/* 268 */ IRQ_UNHANDLED,
/* 269 */ IRQ_UNHANDLED,
/* 270 */ IRQ_UNHANDLED,
/* 271 */ IRQ_UNHANDLED,
/* 272 */ IRQ_UNHANDLED,
/* 273 */ IRQ_UNHANDLED,
/* 274 */ IRQ_UNHANDLED,
/* 275 */ IRQ_UNHANDLED,
/* 276 */ IRQ_UNHANDLED,
/* 277 */ IRQ_UNHANDLED,
/* 278 */ IRQ_UNHANDLED,
/* 279 */ IRQ_UNHANDLED,
/* 280 */ IRQ_UNHANDLED,
/* 281 */ IRQ_UNHANDLED,
/* 282 */ IRQ_UNHANDLED,
/* 283 */ IRQ_UNHANDLED,
/* 284 */ IRQ_UNHANDLED,
/* 285 */ IRQ_UNHANDLED,
/* 286 */ IRQ_UNHANDLED,
/* 287 */ IRQ_UNHANDLED,
/* 288 */ IRQ_UNHANDLED,
/* 289 */ IRQ_UNHANDLED,
/* 290 */ IRQ_UNHANDLED,
/* 291 */ IRQ_UNHANDLED,
/* 292 */ IRQ_UNHANDLED,
/* 293 */ IRQ_UNHANDLED,
/* 294 */ IRQ_UNHANDLED,
/* 295 */ IRQ_UNHANDLED,
/* 296 */ IRQ_UNHANDLED,
/* 297 */ IRQ_UNHANDLED,
/* 298 */ IRQ_UNHANDLED,
/* 299 */ IRQ_UNHANDLED,
/* 300 */ IRQ_UNHANDLED,
/* 301 */ IRQ_UNHANDLED,
/* 302 */ IRQ_UNHANDLED,
/* 303 */ IRQ_UNHANDLED,
/* 304 */ IRQ_UNHANDLED,
/* 305 */ IRQ_UNHANDLED,
/* 306 */ IRQ_UNHANDLED,
/* 307 */ IRQ_UNHANDLED,
/* 308 */ IRQ_UNHANDLED,
/* 309 */ IRQ_UNHANDLED,
/* 310 */ IRQ_UNHANDLED,
/* 311 */ IRQ_UNHANDLED,
/* 312 */ IRQ_UNHANDLED,
/* 313 */ IRQ_UNHANDLED,
/* 314 */ IRQ_UNHANDLED,
/* 315 */ IRQ_UNHANDLED,
/* 316 */ IRQ_UNHANDLED,
/* 317 */ IRQ_UNHANDLED,
/* 318 */ IRQ_UNHANDLED,
/* 319 */ IRQ_UNHANDLED,
/* 320 */ IRQ_UNHANDLED,
/* 321 */ IRQ_UNHANDLED,
/* 322 */ IRQ_UNHANDLED,
/* 323 */ IRQ_UNHANDLED,
/* 324 */ IRQ_UNHANDLED,
/* 325 */ IRQ_UNHANDLED,
/* 326 */ OS_IRQ_SpiIsrTx_1,
/* 327 */ IRQ_UNHANDLED,
/* 328 */ OS_IRQ_SpiIsrTx_2,
/* 329 */ IRQ_UNHANDLED,
/* 330 */ IRQ_UNHANDLED,
/* 331 */ IRQ_UNHANDLED,
/* 332 */ IRQ_UNHANDLED,
/* 333 */ IRQ_UNHANDLED,
/* 334 */ IRQ_UNHANDLED,
/* 335 */ IRQ_UNHANDLED,
/* 336 */ IRQ_UNHANDLED,
/* 337 */ IRQ_UNHANDLED,
/* 338 */ IRQ_UNHANDLED,
/* 339 */ IRQ_UNHANDLED,
/* 340 */ IRQ_UNHANDLED,
/* 341 */ IRQ_UNHANDLED,
/* 342 */ IRQ_UNHANDLED,
/* 343 */ IRQ_UNHANDLED,
/* 344 */ IRQ_UNHANDLED,
/* 345 */ IRQ_UNHANDLED,
/* 346 */ IRQ_UNHANDLED,
/* 347 */ IRQ_UNHANDLED,
/* 348 */ IRQ_UNHANDLED,
/* 349 */ IRQ_UNHANDLED,
/* 350 */ IRQ_UNHANDLED,
/* 351 */ IRQ_UNHANDLED,
/* 352 */ IRQ_UNHANDLED,
/* 353 */ IRQ_UNHANDLED,
/* 354 */ IRQ_UNHANDLED,
/* 355 */ IRQ_UNHANDLED,
/* 356 */ IRQ_UNHANDLED,
/* 357 */ IRQ_UNHANDLED,
/* 358 */ IRQ_UNHANDLED,
/* 359 */ IRQ_UNHANDLED,
/* 360 */ IRQ_UNHANDLED,
/* 361 */ IRQ_UNHANDLED,
/* 362 */ IRQ_UNHANDLED,
/* 363 */ IRQ_UNHANDLED,
/* 364 */ IRQ_UNHANDLED,
/* 365 */ IRQ_UNHANDLED,
/* 366 */ IRQ_UNHANDLED,
/* 367 */ IRQ_UNHANDLED,
/* 368 */ IRQ_UNHANDLED,
/* 369 */ IRQ_UNHANDLED,
/* 370 */ IRQ_UNHANDLED,
/* 371 */ IRQ_UNHANDLED,
/* 372 */ IRQ_UNHANDLED,
/* 373 */ IRQ_UNHANDLED,
/* 374 */ IRQ_UNHANDLED,
/* 375 */ IRQ_UNHANDLED,
/* 376 */ IRQ_UNHANDLED,
/* 377 */ IRQ_UNHANDLED,
/* 378 */ IRQ_UNHANDLED,
/* 379 */ IRQ_UNHANDLED,
/* 380 */ IRQ_UNHANDLED,
/* 381 */ IRQ_UNHANDLED,
/* 382 */ IRQ_UNHANDLED,
/* 383 */ IRQ_UNHANDLED,
/* 384 */ IRQ_UNHANDLED,
/* 385 */ IRQ_UNHANDLED,
/* 386 */ IRQ_UNHANDLED,
/* 387 */ IRQ_UNHANDLED,
/* 388 */ IRQ_UNHANDLED,
/* 389 */ IRQ_UNHANDLED,
/* 390 */ IRQ_UNHANDLED,
/* 391 */ IRQ_UNHANDLED,
/* 392 */ IRQ_UNHANDLED,
/* 393 */ IRQ_UNHANDLED,
/* 394 */ IRQ_UNHANDLED,
/* 395 */ IRQ_UNHANDLED,
/* 396 */ IRQ_UNHANDLED,
/* 397 */ IRQ_UNHANDLED,
/* 398 */ IRQ_UNHANDLED,
/* 399 */ IRQ_UNHANDLED,
/* 400 */ IRQ_UNHANDLED,
/* 401 */ IRQ_UNHANDLED,
/* 402 */ IRQ_UNHANDLED,
/* 403 */ IRQ_UNHANDLED,
/* 404 */ IRQ_UNHANDLED,
/* 405 */ IRQ_UNHANDLED,
/* 406 */ IRQ_UNHANDLED,
/* 407 */ IRQ_UNHANDLED,
/* 408 */ IRQ_UNHANDLED,
/* 409 */ IRQ_UNHANDLED,
/* 410 */ IRQ_UNHANDLED,
/* 411 */ IRQ_UNHANDLED,
/* 412 */ IRQ_UNHANDLED,
/* 413 */ IRQ_UNHANDLED,
/* 414 */ IRQ_UNHANDLED,
/* 415 */ IRQ_UNHANDLED,
/* 416 */ IRQ_UNHANDLED,
/* 417 */ IRQ_UNHANDLED,
/* 418 */ IRQ_UNHANDLED,
/* 419 */ IRQ_UNHANDLED,
/* 420 */ IRQ_UNHANDLED,
/* 421 */ IRQ_UNHANDLED,
/* 422 */ IRQ_UNHANDLED,
/* 423 */ IRQ_UNHANDLED,
/* 424 */ IRQ_UNHANDLED,
/* 425 */ IRQ_UNHANDLED,
/* 426 */ IRQ_UNHANDLED,
/* 427 */ IRQ_UNHANDLED,
/* 428 */ IRQ_UNHANDLED,
/* 429 */ IRQ_UNHANDLED,
/* 430 */ IRQ_UNHANDLED,
/* 431 */ IRQ_UNHANDLED,
/* 432 */ IRQ_UNHANDLED,
/* 433 */ IRQ_UNHANDLED,
/* 434 */ IRQ_UNHANDLED,
/* 435 */ IRQ_UNHANDLED,
/* 436 */ IRQ_UNHANDLED,
/* 437 */ IRQ_UNHANDLED,
/* 438 */ IRQ_UNHANDLED,
/* 439 */ IRQ_UNHANDLED,
/* 440 */ IRQ_UNHANDLED,
/* 441 */ IRQ_UNHANDLED,
/* 442 */ IRQ_UNHANDLED,
/* 443 */ IRQ_UNHANDLED,
/* 444 */ IRQ_UNHANDLED,
/* 445 */ IRQ_UNHANDLED,
/* 446 */ IRQ_UNHANDLED,
/* 447 */ IRQ_UNHANDLED,
/* 448 */ IRQ_UNHANDLED,
/* 449 */ IRQ_UNHANDLED,
/* 450 */ IRQ_UNHANDLED,
/* 451 */ IRQ_UNHANDLED,
/* 452 */ IRQ_UNHANDLED,
/* 453 */ IRQ_UNHANDLED,
/* 454 */ IRQ_UNHANDLED,
/* 455 */ IRQ_UNHANDLED,
/* 456 */ IRQ_UNHANDLED,
/* 457 */ IRQ_UNHANDLED,
/* 458 */ IRQ_UNHANDLED,
/* 459 */ IRQ_UNHANDLED,
/* 460 */ IRQ_UNHANDLED,
/* 461 */ IRQ_UNHANDLED,
/* 462 */ IRQ_UNHANDLED,
/* 463 */ IRQ_UNHANDLED,
/* 464 */ IRQ_UNHANDLED,
/* 465 */ IRQ_UNHANDLED,
/* 466 */ IRQ_UNHANDLED,
/* 467 */ IRQ_UNHANDLED,
/* 468 */ IRQ_UNHANDLED,
/* 469 */ IRQ_UNHANDLED,
/* 470 */ IRQ_UNHANDLED,
/* 471 */ IRQ_UNHANDLED,
/* 472 */ IRQ_UNHANDLED,
/* 473 */ IRQ_UNHANDLED,
};

/**********************************************************************************************************************
*  END OF FILE: VttCntrl_Cfg.c
*********************************************************************************************************************/ 
